In [ ]:
import numpy as np
from scipy.optimize import minimize

In [ ]:
def neg_profit(price):
    demand = 3777178*(price[0]**(-2.154))
    revenue = price[0]*demand
    cost = demand*50
    profit = revenue-cost
    return(-profit)


In [ ]:
# what is the profit for a few prices?
print(-neg_profit([75]))
print(-neg_profit([100]))
print(-neg_profit([150]))

In [ ]:
# the calculus answer
opt_price = -2.154*50/(-2.154 + 1)
print(opt_price)
print(-neg_profit([opt_price]))

In [ ]:
# now use scipy.optimize to solve the problem
# method should be 'BFGS' or 'L-BFGS-B' or 'SLSQP'
# BFGS for completely unconstrained
# L-BFGS-B for just upper and lower bounds on variables - these are called box constraints
# SLSQP for general constraints
# tol tells the solver how accurate to make the solution
# smaller values of tol take longer to solve but are more accurate

In [ ]:
optProfitNLP = minimize(neg_profit,[100],method='L-BFGS-B',bounds=[(0,1000)],tol=1e-8) 

In [ ]:
optProfitNLP.x

In [ ]:
-optProfitNLP.fun

In [ ]:
# starting at different places may lead to different solutions
optProfitNLP = minimize(neg_profit,[75],method='L-BFGS-B',bounds=[(0,1000)])
print(optProfitNLP.x)
print(-optProfitNLP.fun)
# usually not much difference for convex programs

# 2 variable NLP

In [ ]:
def neg_profit2(x):
    # x[0] is price
    # x[1] is number manufactured
    
    demand = 3777178*x[0]**(-2.154)
    num_sold = min(demand,x[1])
    revenue = num_sold*x[0]
    cost = 50*x[1]
    
    profit = revenue-cost
    return -profit

In [ ]:
print(-neg_profit2([100,180]))
print(-neg_profit2([95,175]))

In [ ]:
optProfitNLP2 = minimize(neg_profit2,[90,200],method='L-BFGS-B',bounds=[(0,1000),(0,1000)])
print(-optProfitNLP2.fun)
print(optProfitNLP2.x)

In [ ]:
-neg_profit2([optProfitNLP.x[0],3777178*optProfitNLP.x[0]**(-2.154)])

In [5]:
def obj(xy):
    # xy[0] is x location
    # xy[1] is y location
    
    distance1 = np.sqrt((5-xy[0])**2 + (10-xy[1])**2)
    distance2 = np.sqrt((10-xy[0])**2 + (5-xy[1])**2)
    distance3 = np.sqrt((0-xy[0])**2 + (12-xy[1])**2)
    distance4 = np.sqrt((12-xy[0])**2 + (0-xy[1])**2)
    
    return 2*(distance1*200 + distance2*150 + distance3*200 + distance4*300) 

In [29]:
print(obj([0,0]))
print(obj([3,5]))

19826.237921249263
13477.753249791565


In [30]:
best_loc = minimize(obj,[0,0],method='BFGS')

In [31]:
best_loc.x

array([9.31416525, 5.02870536])

In [32]:
best_loc.fun

10913.07937502574

In [10]:
# inequality constraints must be >= 0! 
# that means the constraint that x[1] >= x[0] must be written as x[1] - x[0] >= 0
# then we just need a function to return x[1]-x[0]
# and the solver will know that this should be >= 0
# it works similary for equality constraints...
# equality constraints must be written as a function(x) = 0


def confun(x):
    return x[1]-x[0]

In [33]:
# now we create a dictionary telling the solver what type of constraint and what the function is
# ineq means inequility, or 'eq',conf --- 2 keys
# ineq means >
constr1 = {'type':'ineq', 'fun': confun}
# then we put all our constraint dictionaries into a list
constraints = [constr1]

In [12]:
best_loc_north = minimize(obj,[3,2],constraints=constraints)

In [13]:
best_loc_north.x

array([6.93579245, 6.93579245])

In [14]:
best_loc_north.fun

11124.981578185989

In [15]:
# if you have an inequality constraint, it's usually best for your initial guess
# to be at a point that does not satisfy the inequality constraint at equality
# for example, if you have a constraint x2 >= x1, it's best not to start at x2 = x1.
#
# but if you have an equality constraint, you should start at a point that satisfies
# that constraint
# for example if you have a constraint x1+x2 = 1, then you should start somewhere 
# like x1 = 0.4, x2 = 0.6


# Jacobian
If we can do a little calculus then we can do better!

The jacobian is the vector of partial derivatives

If we can calculate the jacobian of the objective and each constraint the solver will work better

In [16]:
def con_jac(xy):
    return [-1,1]

In [17]:
con1 = constr1 = {'type':'ineq', 'fun': confun, 'jac': con_jac}
con = [con1]

In [18]:
def obj_jac(xy):
    dd1dx = 0.5/np.sqrt((5-xy[0])**2 + (10-xy[1])**2)*2*(xy[0]-5)
    dd1dy = 0.5/np.sqrt((5-xy[0])**2 + (10-xy[1])**2)*2*(xy[1]-10)
    dd2dx = 0.5/np.sqrt((10-xy[0])**2 + (5-xy[1])**2)*2*(xy[0]-10)
    dd2dy = 0.5/np.sqrt((10-xy[0])**2 + (5-xy[1])**2)*2*(xy[1]-5)
    dd3dx = 0.5/np.sqrt((0-xy[0])**2 + (12-xy[1])**2)*2*(xy[0]-0)
    dd3dy = 0.5/np.sqrt((0-xy[0])**2 + (12-xy[1])**2)*2*(xy[1]-12)
    dd4dx = 0.5/np.sqrt((12-xy[0])**2 + (0-xy[1])**2)*2*(xy[0]-12)
    dd4dy = 0.5/np.sqrt((12-xy[0])**2 + (0-xy[1])**2)*2*(xy[1]-0)
    
    return [2*(dd1dx*200 + dd2dx*150 + dd3dx*200 + dd4dx*300), 2*(dd1dy*200 + dd2dy*150 + dd3dy*200 + dd4dy*300)]

In [19]:
best_loc_north_withJacobian = minimize(obj,[3,2],constraints=con,jac=obj_jac)

In [20]:
best_loc_north_withJacobian.fun

11124.981578187218

In [21]:
best_loc_north_withJacobian.x

array([6.93579262, 6.93579262])